2.1. INSERT en H_RESERVA, H_OCUPANTE y H_CARGO_RESERVA desde H_DATOS_EXTERNOS

-- Insertar en H_RESERVA
INSERT INTO H_RESERVA (CODIGO_RESERVA, NUM_HABITACION, CHECK_IN, CHECK_OUT, MONTO_TOTAL, SALDO, ESTADO, TIPO)
SELECT 
    SEQ_H_RESERVA.NEXTVAL, -- Asignación del ID usando una secuencia o identidad
    DE.NUM_HABITACION,
    DE.FECHA_CHECK_IN,
    DE.FECHA_CHECK_OUT,
    0, -- MONTO_TOTAL = 0
    0, -- SALDO = 0
    'C', -- ESTADO = 'Confirmado'
    'R'  -- TIPO = 'Reserva'
FROM H_DATOS_EXTERNOS DE;

-- Insertar en H_OCUPANTE
INSERT INTO H_OCUPANTE (CODIGO_OCUPANTE, CODIGO_RESERVA, NOMBRE_OCUPANTE, TIPO, FECHA_SALIDA)
SELECT 
    SEQ_H_OCUPANTE.NEXTVAL, -- Asignación del ID usando una secuencia o identidad
    R.CODIGO_RESERVA,
    DE.NOMBRE_OCUPANTE,
    'O',  -- TIPO = 'Ocupante'
    NULL  -- FECHA_SALIDA = NULL
FROM H_DATOS_EXTERNOS DE
JOIN H_RESERVA R ON R.NUM_HABITACION = DE.NUM_HABITACION AND R.CHECK_IN = DE.FECHA_CHECK_IN;

-- Insertar en H_CARGO_RESERVA
INSERT INTO H_CARGO_RESERVA (CODIGO_CARGO, CODIGO_RESERVA, PRECIO_UNITARIO, CANTIDAD, APLICAR_COBRO, CODIGO_FACTURA, TIPO)
SELECT 
    SEQ_H_CARGO_RESERVA.NEXTVAL, -- Asignación del ID usando una secuencia o identidad
    R.CODIGO_RESERVA,
    DE.PRECIO_UNITARIO,
    DE.CANTIDAD,
    'S',  -- APLICAR_COBRO = 'S'
    NULL, -- CODIGO_FACTURA = NULL
    'C'  -- TIPO = 'Cargo'
FROM H_DATOS_EXTERNOS DE
JOIN H_RESERVA R ON R.NUM_HABITACION = DE.NUM_HABITACION AND R.CHECK_IN = DE.FECHA_CHECK_IN;



2.2. INSERT en H_FACTURA_VENTA para la reserva de Julio Castillo Veron

-- Obtener último número de factura y número de timbrado vigente
WITH ULTIMO_NUMERO_FACTURA AS (
    SELECT MAX(CODIGO) AS ULTIMO_CODIGO_FACTURA, MAX(NUMERO_FACTURA) AS ULTIMO_NUMERO_FACTURA
    FROM H_FACTURA_VENTA
),
TIMBRADO_VIGENTE AS (
    SELECT NUMERO_TIMBRADO, MAX(NUMERO_TIMBRADO) AS NUMERO_TIMBRADO_VIGENTE
    FROM H_TIMBRADO
    WHERE FECHA_INICIO <= SYSDATE AND FECHA_FIN >= SYSDATE
)
-- Insertar en H_FACTURA_VENTA
INSERT INTO H_FACTURA_VENTA (CODIGO, FECHA_EMISION, FECHA_CARGA, NUMERO_FACTURA, NUMERO_TIMBRADO, MONTO_GRAVADO, MONTO_IVA, MONTO_EXENTO, CODIGO_RESERVA)
SELECT 
    ULTIMO_NUMERO_FACTURA.ULTIMO_CODIGO_FACTURA + 1,
    SYSDATE,  -- Fecha de emisión
    SYSDATE,  -- Fecha de carga
    ULTIMO_NUMERO_FACTURA.ULTIMO_NUMERO_FACTURA + 1,
    TIMBRADO_VIGENTE.NUMERO_TIMBRADO_VIGENTE,
    NVL(SUM(CASE WHEN CR.PORC_IVA <> 0 THEN CR.PRECIO_UNITARIO * CR.CANTIDAD ELSE 0 END), 0) 
    + ((R.CHECK_OUT - R.CHECK_IN) * H.PRECIO), -- Monto Gravado
    NVL(SUM(CASE WHEN CR.PORC_IVA <> 0 THEN (CR.PRECIO_UNITARIO * CR.CANTIDAD) / 
    CASE CR.PORC_IVA WHEN 10 THEN 11 WHEN 5 THEN 21 END ELSE 0 END), 0) 
    + ((R.CHECK_OUT - R.CHECK_IN) * H.PRECIO / 11), -- Monto IVA
    NVL(SUM(CASE WHEN CR.PORC_IVA = 0 THEN CR.PRECIO_UNITARIO * CR.CANTIDAD ELSE 0 END), 0), -- Monto Exento
    R.CODIGO_RESERVA
FROM H_RESERVA R
JOIN H_OCUPANTE O ON R.CODIGO_RESERVA = O.CODIGO_RESERVA
JOIN H_HABITACION H ON R.NUM_HABITACION = H.NUMERO
LEFT JOIN H_CARGO_RESERVA CR ON R.CODIGO_RESERVA = CR.CODIGO_RESERVA
JOIN ULTIMO_NUMERO_FACTURA ON 1 = 1
JOIN TIMBRADO_VIGENTE ON 1 = 1
WHERE O.NOMBRE_OCUPANTE = 'Julio Castillo Veron'
GROUP BY R.CODIGO_RESERVA, R.CHECK_OUT, R.CHECK_IN, H.PRECIO, 
ULTIMO_NUMERO_FACTURA.ULTIMO_CODIGO_FACTURA, 
ULTIMO_NUMERO_FACTURA.ULTIMO_NUMERO_FACTURA, 
TIMBRADO_VIGENTE.NUMERO_TIMBRADO_VIGENTE;



2.3. Actualizar el campo CODIGO_FACTURA en H_CARGO_RESERVA

-- Actualizar CODIGO_FACTURA en H_CARGO_RESERVA
UPDATE H_CARGO_RESERVA CR
SET CODIGO_FACTURA = (
    SELECT FV.CODIGO
    FROM H_FACTURA_VENTA FV
    JOIN H_RESERVA R ON FV.CODIGO_RESERVA = R.CODIGO_RESERVA
    JOIN H_OCUPANTE O ON R.CODIGO_RESERVA = O.CODIGO_RESERVA
    WHERE O.NOMBRE_OCUPANTE = 'Julio Castillo Veron'
)
WHERE CR.CODIGO_RESERVA = (
    SELECT R.CODIGO_RESERVA
    FROM H_RESERVA R
    JOIN H_OCUPANTE O ON R.CODIGO_RESERVA = O.CODIGO_RESERVA
    WHERE O.NOMBRE_OCUPANTE = 'Julio Castillo Veron'
);


