SELECT A.NOMBRE_AREA, 
TO_CHAR(MAX (CS.ASIGNACION),'999G999G999') AS MAXIMO,
TO_CHAR(MIN(CS.ASIGNACION),'999G999G999') AS MINIMO
FROM B_POSICION_ACTUAL PA JOIN B_EMPLEADOS E 
ON PA.CEDULA=E.CEDULA 
JOIN B_CATEGORIAS_SALARIALES CS
ON CS.COD_CATEGORIA=PA.COD_CATEGORIA
JOIN B_AREAS A 
ON A.ID=PA.ID_AREA
WHERE PA.FECHA_FIN IS NULL
AND CS.FECHA_FIN IS NULL
GROUP BY A.NOMBRE_AREA
;

SELECT 
E.NOMBRE||' '||E.APELLIDO NOMBRES,
CS.NOMBRE_CAT CATEGORIA, 
TO_CHAR(CS.ASIGNACION,'999G999G999') SALARIO,
A.NOMBRE_AREA AREA 
FROM B_POSICION_ACTUAL PA JOIN B_EMPLEADOS E 
	ON PA.CEDULA=E.CEDULA 
JOIN B_CATEGORIAS_SALARIALES CS
	ON CS.COD_CATEGORIA=PA.COD_CATEGORIA
JOIN B_AREAS A 
	ON A.ID=PA.ID_AREA
WHERE PA.FECHA_FIN IS NULL
	AND CS.FECHA_FIN IS NULL
	AND CS.ASIGNACION = (SELECT MAX(CS.ASIGNACION)MAXIMO 
							FROM B_POSICION_ACTUAL PA 
							JOIN B_EMPLEADOS E 
							ON PA.CEDULA=E.CEDULA 
							JOIN B_CATEGORIAS_SALARIALES CS
							ON CS.COD_CATEGORIA=PA.COD_CATEGORIA
							WHERE PA.FECHA_FIN IS NULL
							AND CS.FECHA_FIN IS NULL
						)
;

WITH SALARIOS AS 
(SELECT E.NOMBRE, CS.NOMBRE_CAT CATEGORIA, CS.ASIGNACION, A.NOMBRE_AREA 
		FROM B_POSICION_ACTUAL PA 
		JOIN B_EMPLEADOS E 
			ON PA.CEDULA=E.CEDULA 
		JOIN B_CATEGORIAS_SALARIALES CS
			ON CS.COD_CATEGORIA=PA.COD_CATEGORIA
		JOIN B_AREAS A 
			ON A.ID=PA.ID_AREA
		WHERE PA.FECHA_FIN IS NULL
		AND CS.FECHA_FIN IS NULL
		)
SELECT SA.NOMBRE,SA.CATEGORIA, SA.ASIGNACION, SA.NOMBRE_AREA
FROM SALARIOS SA 
WHERE SA.ASIGNACION =(SELECT MAX(S.ASIGNACION)maximo 
						FROM SALARIOS S)
			;

SELECT L.NOMBRE LOCALIDAD,
COUNT(*) CANTIDAD
FROM B_LOCALIDAD L LEFT OUTER JOIN B_PERSONAS P 
	ON L.ID=P.ID_LOCALIDAD 
	AND P.ES_CLIENTE='S'
GROUP BY L.NOMBRE
ORDER BY 1
;

SELECT L.NOMBRE 
FROM B_LOCALIDAD L 
WHERE L.ID IN
 (SELECT ID_LOCALIDAD FROM B_PERSONAS WHERE ES_CLIENTE='S')
ORDER BY 1;

SELECT L.NOMBRE 
FROM B_LOCALIDAD L 
WHERE EXISTS
 (SELECT ID_LOCALIDAD 
	FROM B_PERSONAS P
	WHERE ES_CLIENTE='S'
	AND P.ID_LOCALIDAD=L.ID)
ORDER BY 1;

SELECT L.NOMBRE 
FROM B_LOCALIDAD L 
WHERE NOT EXISTS
 (SELECT 'X' 
	FROM B_PERSONAS P
	WHERE ES_CLIENTE='S'
	AND P.ID_LOCALIDAD=L.ID)
ORDER BY 1;

SELECT AR.NOMBRE, 
VE.CANT_VENTAS,
VE.TOT_VENTAS,
CO.CANT_COMPRAS,
CO.TOT_COMPRAS
FROM B_ARTICULOS AR 
LEFT JOIN 
	(SELECT A.ID,
	SUM(DV.CANTIDAD) CANT_VENTAS,
	SUM(DV.CANTIDAD*DV.PRECIO)TOT_VENTAS
	FROM B_ARTICULOS A 
	JOIN B_DETALLE_VENTAS DV 
		ON A.ID=DV.ID_ARTICULO
	JOIN B_VENTAS V 
		ON V.ID=DV.ID_VENTA
	WHERE V.FECHA LIKE '%18'
	GROUP BY A.ID) VE
ON AR.ID=VE.ID
LEFT JOIN 
	(SELECT A.ID,
	SUM(DC.CANTIDAD) CANT_COMPRAS,
	SUM(DC.CANTIDAD*DC.PRECIO_COMPRA)TOT_COMPRAS
	FROM B_ARTICULOS A 
	JOIN B_DETALLE_COMPRAS DC 
		ON A.ID=DC.ID_ARTICULO
	JOIN B_COMPRAS C 
		ON C.ID=DC.ID_COMPRA
	WHERE C.FECHA LIKE '%18'
	GROUP BY A.ID) CO 
ON CO.ID=AR.ID
;
SELECT 
	SUBSTR(A.NOMBRE,20) NOMBRE,
	SUM(DECODE(TO_CHAR(V.FECHA,'MM'),'01',DV.CANTIDAD,0))ene,
	SUM(DECODE(TO_CHAR(V.FECHA,'MM'),'02',DV.CANTIDAD,0)) feb
	FROM B_ARTICULOS A 
	JOIN B_DETALLE_VENTAS DV 
		ON A.ID=DV.ID_ARTICULO
	JOIN B_VENTAS V 
		ON V.ID=DV.ID_VENTA
	WHERE V.FECHA LIKE '%18'
	GROUP BY A.NOMBRE
	;


(CASE WHEN 
		EXTRACT(MONTH FROM V.FECHA)=1 
			THEN DV.CANTIDAD 
		ELSE 
	END)

	



