-- a. Las tablas descriptas en el cuadro más abajo, deben ser creadas con las reglas de integridad
-- relacional (PK, FK, Checks) definidas.
-- b. Incluir los comentarios a nivel de las tablas


CREATE TABLE H_CARGO_RESERVA
(
	CODIGO_CARGO              NUMBER(10) GENERATED BY DEFAULT AS IDENTITY 
	(START WITH 1 MINVALUE 1 MAXVALUE 9999999999 INCREMENT BY 1)
	NOT NULL CONSTRAINT  PK_COD_CARGO PRIMARY KEY ,
	CODIGO_RESERVA            NUMBER(12) NOT NULL ,
	ID_PROD_SERV              NUMBER(5) NOT NULL ,
	PRECIO_UNITARIO           NUMBER(10) NOT NULL ,
	CANTIDAD                  NUMBER(5) NOT NULL ,
	APLICAR_COBRO             VARCHAR2(1) DEFAULT 'S' NOT NULL 
	CHECK (APLICAR_COBRO IN ('S', 'N')),
	CODIGO_FACTURA            NUMBER(15),

CONSTRAINT FK_COD_RESERVA FOREIGN KEY(CODIGO_RESERVA)
REFERENCES Z(Z_id) ,
CONSTRAINT FK_ID_PROD_SERV FOREIGN KEY(ID_PROD_SERV)
REFERENCES X(X_id) 
);

COMMENT ON TABLE H_CARGO_RESERVA IS 'En esta tabla se registran todos los productos, servicios
y cargos que deben ser cobrados al huésped. Ej: Servicio de lavandería, Consumo de bebida, Saldo
reserva habitación, etc. Cuando un cargo tiene asociado un código de factura, significa que ya fue abonado.
Existen productos/servicios que se entregan al huésped como gentileza, y estos no deben ser facturados.';





CREATE TABLE H_TIPO_DOCUMENTO
(
	DESC_ABREVIADA     VARCHAR2(10) NOT NULL ,
	DESC_LARGA           VARCHAR2(100) NOT NULL ,
CONSTRAINT  PK_ID_TIPO_DOC PRIMARY KEY (DESC_ABREVIADA)
);


COMMENT ON TABLE H_TIPO_DOCUMENTO IS 'En esta tabla se registran los tipos de documentos de identidad que podrían presentar los huéspedes. Ej: CI, DNI, PASAPORTE, etc.';


ALTER TABLE H_HABITACION
	ADD (CONSTRAINT CATEGORIA_HABITACION_FK FOREIGN KEY (COD_CATEGORIA) REFERENCES H_CATEGORIA (CODIGO));


ALTER TABLE H_HUESPED
	ADD (CONSTRAINT TIPO_DOCUMENTO_HUESPUED_FK FOREIGN KEY (TIPO_DOCUMENTO) REFERENCES H_TIPO_DOCUMENTO (DESC_ABREVIADA));



ALTER TABLE H_MOVIMIENTO_PRODUCTO
	ADD (CONSTRAINT PRODUCTO_SERVICIO_MOVIMIENT996 FOREIGN KEY (ID_PRODUCTO) REFERENCES H_PRODUCTO_SERVICIO (ID));
