
CREATE MATERIALIZED VIEW V_CARGOS_HUESPEDES
REFRESH COMPLETE
START WITH TRUNC(SYSDATE) + 5/24 -- Comienza a las 5:00 am
NEXT TRUNC(SYSDATE + 1) + 5/24 -- Se actualiza todos los días a las 5:00 am
AS
SELECT 
    H.NUMERO_HABITACION AS HABITACION,
    R.CODIGO_RESERVA,
    C.DESCRIPCION AS CATEGORIA,
    R.CANTIDAD_OCUPANTES,
    
    -- Calcular el costo de la habitación
    (R.CANTIDAD_DIAS * H.COSTO_POR_NOCHE 
    + DECODE(SIGN(R.CANTIDAD_OCUPANTES - C.CAPACIDAD_MAXIMA), 1, 
             (R.CANTIDAD_OCUPANTES - C.CAPACIDAD_MAXIMA) * C.COSTO_ADICIONAL_HUESPED, 
             0)) AS COSTO_HABITACION,
             
    -- Calcular otros cargos pendientes de cobro
    NVL(SUM(CR.PRECIO_UNITARIO * CR.CANTIDAD), 0) AS OTROS_CARGOS

FROM 
    HABITACIONES H
    JOIN RESERVAS R ON H.ID_HABITACION = R.ID_HABITACION
    JOIN CATEGORIAS C ON H.ID_CATEGORIA = C.ID_CATEGORIA
    LEFT JOIN CARGOS_RESERVA CR ON R.CODIGO_RESERVA = CR.CODIGO_RESERVA 
       AND CR.APLICAR_COBRO = 'S' 
       AND CR.CODIGO_FACTURA IS NULL

WHERE 
    R.ESTADO = 'OCUPADA'
    AND R.CHECKOUT_DATE BETWEEN TO_DATE('2024-08-15', 'YYYY-MM-DD') AND TO_DATE('2024-08-19', 'YYYY-MM-DD')

GROUP BY 
    H.NUMERO_HABITACION,
    R.CODIGO_RESERVA,
    C.DESCRIPCION,
    R.CANTIDAD_OCUPANTES,
    R.CANTIDAD_DIAS,
    H.COSTO_POR_NOCHE,
    C.CAPACIDAD_MAXIMA,
    C.COSTO_ADICIONAL_HUESPED;
